[book]
authors = ["a327ex"]
language = "en"
multilingual = false
src = "src"
title = "ğ•­ğ–„ğ•¿ğ•®ğ•»ğ•¬ğ•¿ğ•³ ğ–‰ğ–‘ğ–”ğ–Œğ–˜"

[output.html]
theme = "my-theme"
default-theme = "ayu"
preferred-dark-theme = "ayu"