[book]
authors = ["a327ex"]
language = "en"
multilingual = false
src = "src"
title = "ğ•­ğ–„ğ•¿ğ•®ğ•»ğ•¬ğ•¿ğ•³ ğ–‰ğ–‘ğ–”ğ–Œğ–˜"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/scillidan/BYTEPATH-blogs"
git-repository-icon = "fa-github"