[book]
title = "ğ•­ğ–„ğ•¿ğ•®ğ•»ğ•¬ğ•¿ğ•³ ğ–‰ğ–‘ğ–”ğ–Œğ–˜"
author = "a327ex"
description = "A DevLog/Blog book binding from BYTEPATH by a327ex."
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/scillidan/BYTEPATH-blogs"
git-repository-icon = "fa-github"

[output.epub]
# additional-css = ["./path/to/main.css"]
# use-default-css = false
# cover-image = "ebook-cover.png"
# additional-resources = ["./assets/Open-Sans-Regular.ttf"]
no-section-label = true
curly-quotes = true
epub-version = 3
footnote-backrefs = true